# Generated by Django 6.0.4 on 2026-05-01 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evaluator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.supervisorprofile",
            ),
        ),
        migrations.AddField(
            model_name="evaluationscore",
            name="criterion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.evaluationcriterion",
            ),
        ),
        migrations.AddField(
            model_name="evaluationscore",
            name="evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="issues.evaluation",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="finalresult",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="issues.company",
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="placements",
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="finalresult",
            name="placement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="final_result",
                to="issues.internshipplacement",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="issues.internshipplacement",
            ),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="report_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.reportdefinition",
            ),
        ),
        migrations.AddField(
            model_name="supervisorassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="supervisorassignment",
            name="placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="issues.internshipplacement",
            ),
        ),
        migrations.AddField(
            model_name="supervisorassignment",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_placements",
                to="users.supervisorprofile",
            ),
        ),
        migrations.AddField(
            model_name="weeklylog",
            name="placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="issues.internshipplacement",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="weekly_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_entries",
                to="issues.weeklylog",
            ),
        ),
        migrations.AddIndex(
            model_name="internshipplacement",
            index=models.Index(
                fields=["status", "start_date"], name="issues_inte_status_d6c89b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supervisorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("placement", "assignment_role"),
                name="one_active_supervisor_per_role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weeklylog",
            unique_together={("placement", "week_number")},
        ),
    ]
